### ISSUE TITLE
Installation Documantation errors

### ISSUE THREAD

**Issue by AlexBaturin** [icoz/pysymo#2]
`tools/initdb.py => tools/init_db.py`
если я запускаю из корневой папки pysymo:
`python tools/init_medb.py`
получаю ошибку:

```
OK: Collection 'medb' and indexes were created in 'rsyslog' database
OK: Now load medb into 'rsyslog' database
unzip:  cannot find or open ../data/medb.zip, ../data/medb.zip.zip or ../data/medb.zip.ZIP.
Traceback (most recent call last):
  File "tools/init_medb.py", line 45, in <module>
    main()
  File "tools/init_medb.py", line 32, in main
    f = open('medb.txt', 'r')
IOError: [Errno 2] No such file or directory: 'medb.txt'
```

отсутствует пример задач _cron_
_было бы не плохо показать как часто запускать обработку с точки зрения разработчика._
### _За работу огромное спасибо!!_

Хорошо добавить пример запуска логгера из под apache с модулем mod_wsgi

pysymo.conf (Apache >= 2.0)

```
<VirtualHost *:80>
        ServerName pysymo.example.com
        WSGIScriptReloading On
        WSGIScriptAlias / /opt/pysymo/apache.wsgi
        <Directory /opt/pysymo/app/>
                Order allow,deny
                Allow from all
        </Directory>
        Alias /static /opt/pysymo/app/static
        <Directory /opt/pysymo/app/static/>
                Order allow,deny
                Allow from all
        </Directory>
</VirtualHost>
```

apache.wsgi:

```
#!/usr/bin/python
import sys
sys.path.insert(0,"/opt/pysymo/")
from app import app as application
application.secret_key = 'some_super_secret_key'
```

Это мой рабочий вариант.

в корне проекта можно создать файл _requirements.txt_ с содержимым:

```
Flask
Flask-WTF
Jinja2
WTForms
pymongo
flup
flask-paginate
flask-login
pycrypto
python-ldap
Babel
Flask-Babel
```

и ставить все вместе одной командой `pip install -r requirements.txt`

Для незнающих питон это поможет, только указать что должен стоять в системе pip.

**Comment by icoz** [comment]
Спасибо за информацию.
Обязательно учтем.
19 авг. 2015 г. 1:34 пользователь "Alex Baturin" notifications@github.com
написал:
